# Generated by Django 4.2.5 on 2023-10-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Total', models.CharField(max_length=2048)),
                ('Date', models.CharField(max_length=2048)),
                ('Time', models.CharField(max_length=2048)),
                ('From', models.CharField(max_length=2048)),
                ('To', models.CharField(max_length=2048)),
                ('Distance', models.CharField(max_length=2048)),
            ],
        ),
    ]
